<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BestCrush.NetworkProbe</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpPcap" Version="6.3.1" />
    <PackageReference Include="PacketDotNet" Version="1.4.8" />
  </ItemGroup>

  <ItemGroup>
    <None Update="protocol-map.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
