// <auto-generated />
using System;
using BestCrush.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BestCrush.Domain.Migrations
{
    [DbContext(typeof(BestCrushDbContext))]
    [Migration("20260911063748_AddCrushValueDiscount")]
    partial class AddCrushValueDiscount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("BestCrush.Domain.Models.CoefficientObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CoefficientPercent")
                        .HasColumnType("REAL");

                    b.Property<long>("DofusDbId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DofusDbId", "ServerName", "ObservedAtUtc");

                    b.ToTable("CoefficientObservations");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.CrushHistoryEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CoefficientPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("CoefficientSource")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DofusDbIconId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DofusDbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowY")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "DofusDbId");

                    b.ToTable("CrushHistoryEquipments");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.CrushHistoryRune", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DofusDbIconId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DofusDbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuneName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "DofusDbId");

                    b.ToTable("CrushHistoryRunes");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.CrushHistoryRuneLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LotPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LotQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PriceObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PriceSource")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RuneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuneId");

                    b.ToTable("CrushHistoryRuneLots");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.CrushHistorySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("DiscountedTotalValue")
                        .HasColumnType("REAL");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ServerName", "CompletedAtUtc");

                    b.ToTable("CrushHistorySessions");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DofusDbIconId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DofusDbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("DofusDbId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.EquipmentRecipeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientEquipmentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("IngredientEquipmentId");

                    b.ToTable("EquipmentRecipeEntries");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.ItemCharacteristicLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Characteristic")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("From")
                        .HasColumnType("INTEGER");

                    b.Property<int>("To")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ItemCharacteristicLine");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.MarketPriceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DofusDbId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjectType", "DofusDbId", "ServerName", "Quantity", "ObservedAtUtc");

                    b.ToTable("MarketPriceObservations");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.RecipeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ResourceId");

                    b.ToTable("RecipeEntry");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DofusDbIconId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DofusDbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("DofusDbId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.Rune", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Characteristic")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DofusDbIconId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DofusDbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("DofusDbId");

                    b.ToTable("Runes");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.Upgrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpgradeDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Upgrades");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.CrushHistoryEquipment", b =>
                {
                    b.HasOne("BestCrush.Domain.Models.CrushHistorySession", "Session")
                        .WithMany("Equipments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.CrushHistoryRune", b =>
                {
                    b.HasOne("BestCrush.Domain.Models.CrushHistorySession", "Session")
                        .WithMany("Runes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.CrushHistoryRuneLot", b =>
                {
                    b.HasOne("BestCrush.Domain.Models.CrushHistoryRune", "Rune")
                        .WithMany("Lots")
                        .HasForeignKey("RuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rune");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.EquipmentRecipeEntry", b =>
                {
                    b.HasOne("BestCrush.Domain.Models.Equipment", "Equipment")
                        .WithMany("EquipmentRecipe")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestCrush.Domain.Models.Equipment", "IngredientEquipment")
                        .WithMany()
                        .HasForeignKey("IngredientEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("IngredientEquipment");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.ItemCharacteristicLine", b =>
                {
                    b.HasOne("BestCrush.Domain.Models.Equipment", "Equipment")
                        .WithMany("Characteristics")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.RecipeEntry", b =>
                {
                    b.HasOne("BestCrush.Domain.Models.Equipment", "Equipment")
                        .WithMany("Recipe")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestCrush.Domain.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.CrushHistoryRune", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.CrushHistorySession", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("Runes");
                });

            modelBuilder.Entity("BestCrush.Domain.Models.Equipment", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("EquipmentRecipe");

                    b.Navigation("Recipe");
                });
#pragma warning restore 612, 618
        }
    }
}
