name: Continuous Deployment - Publish DofusDB CLI

on:
  release:
    types: published
  workflow_dispatch:
    inputs:
      dry-run:
        description: Skip the publication to repos
        required: true
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  compute-version:
    name: Compute version
    uses: ./.github/workflows/reusable-compute-version.yml
    with:
      build-name: release

  build-test:
    name: Build and test DofusDB CLI
    runs-on: ubuntu-latest
    needs: compute-version

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Build
        run: dotnet build DofusSharp.DofusDb.Filter.slnf --configuration Release --property Version=${{ needs.compute-version.outputs.version }}

      - name: Test
        run: dotnet test DofusSharp.DofusDb.Filter.slnf --configuration Release --no-build

  build-publish-binaries:
    name: Publish DofusDB CLI and push to release
    needs: [compute-version, build-test]
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - runner: ubuntu-latest
            rid: linux-x64
            output-name: dofusdb
          - runner: windows-latest
            rid: win-x64
            output-name: dofusdb.exe
          - runner: macos-latest 
            rid: osx-x64
            output-name: dofusdb
        
    runs-on: ${{ matrix.runner }}

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Publish
        run: dotnet publish dofusdb/dofusdb.csproj --output dist/ --configuration Release --property RuntimeIdentifier=${{ matrix.rid }} --property Version=${{ needs.compute-version.outputs.version }}

      - name: Archive binaries
        if: ${{ github.event_name == 'release' }}
        run: |
          cd dist
          7z a -tzip dofusdb-${{ matrix.rid }}.zip ${{ matrix.output-name }}

      - name: Upload binaries to release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/dofusdb-${{ matrix.rid }}.zip
          asset_name: dofusdb-${{ matrix.rid }}.zip
          tag: ${{ github.ref }}

      - name: Upload binaries as artifact
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v5
        with:
          path: dist/${{ matrix.output-name }}
          name: dofusdb-${{ matrix.rid }}
          if-no-files-found: error