name: Reusable - Compute Version

on:
  workflow_call:
    inputs:
      build-name:
        description: The name of the build, defaults to 'build'
        type: string
        default: build

    outputs:
      version:
        description: The version of the application
        value: ${{ jobs.compute_version.outputs.version }}
      version-short:
        description: The version of the application, without build metadata
        value: ${{ jobs.compute_version.outputs.version-short }}


env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

permissions:
  contents: read

jobs:
  compute_version:
    name: Compute version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.compute_version.outputs.version }}
      version-short: ${{ steps.compute_version.outputs.version-short }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install MinVer
        run: dotnet tool install -g minver-cli

      - name: Compute version
        id: compute_version
        env:
          MINVERBUILDMETADATA: ${{ inputs.build-name }}.${{ github.run_id }}.${{ github.run_attempt }}
        run: |
          VERSION=$(minver -t v -v d)
          echo "Version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version-short=${VERSION%%+*}" >> $GITHUB_OUTPUT